### ISSUE TITLE
Populate modal form during onOpen event

### ISSUE THREAD

**Issue by boris-glumpler** [ralphjsmit/tall-interactive#13]
Hello,

More of a question, really... I have a form within a modal and I can't seem to populate it with data. 

The workflow goes a bit like this:

Users can select a country on a map, which then saves it as a relationship. When users then click on the same country again it opens up the edit modal and I pass the id of the country along like so: `$wire.emit('modal:open', 'user-log', id)`. In the `onOpen` method of the modal I then use the `id` to get the country relationship and set some properties:

```php
public function onOpen(array $eventParams, self $formClass): void
{
    $country = current_user()
        ->countries()
        ->where('id', $eventParams[0])
        ->first();

    $formClass->name = $country->name;
    $formClass->private = (bool) $country->meta->private;
}
```

I then tried to fill the form with data:

```php
public function fill(): array
{
    return [
        'name'    => $this->name,
        'private' => $this->private,
    ];
}
```

It doesn't work, tho. This seems to be the order the methods are called in:

On page load:
```
mount
getFormSchema
fill
```

On open:
```
onOpen
getFormSchema 
```

So, the `fill` method never gets called again during `onOpen`. How can I then populate a form with data set during the `onOpen` event?

Cheers!

**Comment by boris-glumpler** [comment]
Looks like I can manually fill the form in `onOpen` like so:

```php
$livewire->form->fill(
    $formClass->fill()
);
```

Is this the recommended way then?

**Comment by ralphjsmit** [comment]
Hey @boris-glumpler, yep that's exactly how it is intended!

For example, this is an alternative approach that comes from one of my projects, where I directly modify two properties in the Livewire `$data` array:

```php
    public function onOpen(array $eventParams, Component $livewire)
    {
        $from = organization()->settings->worktimes['from'] ?? '08:00';
        $to = organization()->settings->worktimes['to'] ?? '17:00';

        $selectedDate = $eventParams[0] ?? null;

        $livewire->data['starts_at'] = carbon($selectedDate)->setTimeFrom($from)->tzXXXXX();
        $livewire->data['ends_at'] = carbon($selectedDate)->setTimeFrom($to)-> tzXXXXX();

        $this->selectedDate = $selectedDate;

        $livewire->data['persons'] = [];
    }
```

**Comment by boris-glumpler** [comment]
Thanks for your reply!
