### ISSUE TITLE
how can I send and get data in livewire component?

### ISSUE THREAD

**Issue by waapatricio** [ralphjsmit/tall-interactive#20]
I have a doubt.
In the case of calling a Livewire component instead of a form, how can I send and get data?

I tried to retrieve the parameters in onOpen, but I believe it is not being called when I create a modal with a component.

`<x-tall-interactive::modal
        id="verify-phone"
        livewire="auth.verify-phone"
        maxWidth="sm"
        hideControls
        :model="$user"
    />`

**Comment by ralphjsmit** [comment]
Hey @waapatricio! The `onOpen()` method will only work on form classes and not on custom Livewire components.

The parameters are passed to the livewire component like you usually do:

```blade
@livewire($livewire, $params)
```

Where $params are all the parameters _except_ these:
```php
        'id',
        'slot',
        'closeOnSubmit',
        'description',
        'dismissable',
        'dismissableWith',
        'form',
        'forceCloseOnSubmit',
        'hideControls',
        'livewire',
        'maxWidth',
        'model',
        'submitWith',
        'title',
```
If you pass any parameters other than the ones above, you can receive them in the `mount()` method of your Livewire component.

So for example, this would work:

```blade
<x-tall-interactive::modal 
    id="verify-phone" 
    livewire="auth.verify-phone" 
    maxWidth="sm" 
    hideControls 
    :model="$user" 
    :user="$user"
    custom="hello world" 
/>
```

```php
class VerifyPhone extends Component
{
    public User $user; 
    
    public function mount(string $custom): void
    {
        //
    }
}
```

The reason that the above parameters are excluded is that those parameters are default parameters claimed/used by the package internally.
